var config = new Array(
  ["v","titanic.mp4"],["v","notitle.mp4"],["v","white.mp4"],["v","chi.mp4"],["p","redRepublic",8],["p","titanic2",8]
)
// TODO:  config of live photos.html, "v" means video,"p" means photos
//        video mode second element represent file name
//        photo mode second element represent floder name,third element represent max-nums of photos,ends with .JPG(on caps)
//        comments in this js also, for example,demo.mp4 comments is 'var demo ="comments"',html tag is allowed in comments
var titanic = "<p>When time comes into the present, people of different ages, genders, political forms, cultural structures and economic models all feel threatened by the anxiety and confusion of The Times. It seems that the world we are experiencing is not the world we are pushing it forward, sometimes even the opposite.</p><p>The work makes use of the realistic context to make scene space fiction, and creates a world of heterotopia through miniaturization model, trying to show the current social status and crowd syndrome under the haze of The Times.</p>";
var notitle = "<p>When we talk about sexual images, it can be thought of as our preliminary understanding of the body. I re-created the preliminary understanding.The video is comprised of elements like flower, blood, water, milk, etc. It is a fusion of nature and the body. For me, it is also a kind of functional body awarness.</p>";
var white = "<p>I named this work 'white', and I want to use white to think about the relationship between existence and non-existence.</p>";
var chi = "<p>Power, jealousy, desire, greed, which is both animality and human nature.</p>";
var redRepublic = "<p>In this space, I am the participant, performer, and viewer.</p> <p>China's socialist practice is unique and far-reaching. In the past the government vigorously promoted collectivism through a passive voice, in an effort to eliminate individualism. This national ideology shaped my generation. However, with the development of Chinese economy and culture, contemporary Chinese citizens have begun to over-promote individualism, emphasizing the development of personalities. Incredibly, the transition from collectivism to individualism has taken only a short period of ten years. At this time, self-awareness has exploded and our generation wants to express ourselves while being trapped in the subconscious of collectivism. It is so powerful that it can be considered a national crisis.</p><p>I do not intend to subjectively evaluate the pros and cons of collectivism and individualism. I am trapped in the conflict between the collective and the individual, and I try to find a balance. This world of red and blue is balanced, and the relationship between the object and the shadow is balanced.</p>";
